# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efac7c4dc86fe84447ed2830b52d7330a47259f904d8d0c1e38100fee6d47fdee4f11331733283c876240e5f8fc64b370c41d8f045ababdfbecc0d146caab6fa

test:
  secret_key_base: 6e33367f17a331752946ff054db5d6737b80321932a6c6eb81794e4703f130875629d93a55d57518810e014e4bdede573e04b0471edd5276b11287a8544b230c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
